FROM blackgolfer/texlive:latest

ARG NB_USER
ARG NB_GROUP
ARG NB_UID

# python3
RUN apt update
RUN apt-get install -y python3 python3-pip --fix-missing

WORKDIR /docs
ADD requirements.txt /docs
RUN python3 -m pip install -U pip
RUN pip3 install Sphinx Pillow
RUN pip3 install -r requirements.txt

RUN useradd --no-create-home -g $NB_GROUP -u $NB_UID $NB_USER

USER $NB_UID
